# Automatic pipeline running when we merge into the main branch.

trigger:
  - main

variables:
  ClientSharedUpdated: false

pool:
  vmImage: ubuntu-latest
  
steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - task: PowerShell@2
    displayName: Check if Client.Shared has been updated
    env:
      NODE_OPTIONS: --max_old_space_size=16384
    inputs:
      targetType: 'inline'
      script: |
          $files=$(git diff HEAD HEAD~ --name-only)
          $temp=$files -split ' '
          $count=$temp.Length
          echo "Total changed $($temp.Length) files"
          for ($i=0; $i -lt $temp.Length; $i++)
          {
                $name=$temp[$i]
              Write-Host "Changed file:" $name
              if ($name -like "src/Web/formsexpress.enotices.client.shared/*")
              {
                    Write-Host "##vso[task.setvariable variable=ClientSharedUpdated]true"
                  Write-Host "ClientSharedUpdated set to true"
                  Break
              }
          }

  - task: NodeTool@0 
    displayName: Install Node.js
    inputs:
      versionSpec: '20.x'
    
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 8.x'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: Install dotnet ef
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global dotnet-ef --version 8.0.1'

  - task: PowerShell@2
    displayName: Display the environment variables
    inputs:
      targetType: 'inline'
      script: 'Get-ChildItem Env: | Sort-Object Name'

  - task: NuGetAuthenticate@1
    displayName: NuGet authenticate

  - task: PowerShell@2
    displayName: NuGet restore
    inputs:
      targetType: 'inline'
      script: 'dotnet restore ./src/FormsExpress.ENotices.sln --configfile ./src/nuget.config --verbosity normal'

  - task: Bash@3
    displayName: Install Azurite
    inputs:
      targetType: 'inline'
      script: |
        npm install -g azurite
        mkdir azurite
        azurite --silent --location azurite --debug azurite\debug.log &

  - task: DotNetCoreCLI@2
    displayName: Run Web API build
    inputs:
      command: 'build'
      projects: '$(System.DefaultWorkingDirectory)/src/Web/FormsExpress.ENotices.WebApi/FormsExpress.ENotices.WebApi.csproj'

  - task: DotNetCoreCLI@2
    displayName: Run Web API tests
    inputs:
      command: 'test'
      projects: '**/Tests/**/*.csproj'
      testRunTitle: 'Web API Tests'

  - task: FileTransform@1
    displayName: Transform Web API appsettings.json with pipeline variables
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/src/Web'
      fileType: 'json'
      targetFiles: 'FormsExpress.ENotices.WebApi/**/appsettings.json'

  - task: DotNetCoreCLI@2
    displayName: Publish Web API for staging
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(System.DefaultWorkingDirectory)/src/Web/FormsExpress.ENotices.WebApi/FormsExpress.ENotices.WebApi.csproj'
      arguments: '--output $(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Create application migrations SQL script
    inputs:
      command: 'custom'
      custom: 'ef'
      arguments: 'migrations script --output $(Build.SourcesDirectory)/SQL/application_migrations.sql --idempotent --project $(Build.SourcesDirectory)/src/Web/FormsExpress.ENotices.WebApi/FormsExpress.ENotices.WebApi.csproj --context ApplicationDbContext'

  - task: PublishBuildArtifacts@1
    displayName: Publish migrations SQL scripts
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/SQL'
      ArtifactName: 'SQLScripts'
    
  - task: npmAuthenticate@0
    inputs:
      workingFile: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.client.shared/.npmrc'
    condition: and(succeeded(), eq(variables['ClientSharedUpdated'], 'true'))

  - script: npm ci
    displayName: 'Client.Shared: npm install'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.client.shared'
    condition: and(succeeded(), eq(variables['ClientSharedUpdated'], 'true'))

  - script: npm run rollup
    displayName: 'Client.Shared: run rollup'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.client.shared'
    condition: and(succeeded(), eq(variables['ClientSharedUpdated'], 'true'))

  - script: |
      output=$(npm publish 2>&1)
      status=$?

      echo "$output"

      if [ $status -eq 0 ]; then
        exit 0
      elif echo "$output" | grep -q "already contains"; then
        echo "Package already exists, moving forward."
        exit 0
      else
        exit 1
      fi
    displayName: 'Client.Shared: npm publish'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.client.shared'
    condition: and(succeeded(), eq(variables['ClientSharedUpdated'], 'true'))

  - task: npmAuthenticate@0
    inputs:
      workingFile: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.dashboard/.npmrc'

  - script: npm install
    displayName: 'Dashboard UI: npm install'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.dashboard'

  - script: npm run lint
    displayName: 'Dashboard UI: run lint'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.dashboard'

  - script: npm run build
    displayName: 'Dashboard UI: build production'
    workingDirectory: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.dashboard'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/src/Web/formsexpress.enotices.dashboard/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/FormsExpress.ENotices.Dashboard.zip'
      replaceExistingArchive: true
      verbose: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ENoticesApps'
      publishLocation: 'Container'

  - script: find .
    displayName: List contents of the folder
